describe("refman", function()
  it("module can be loaded", function()
    local refman = require("refman")
    assert.is_not_nil(refman)
  end)

  it("config has defaults", function()
    local defaults = require("refman.config.defaults")
    assert.is_not_nil(defaults.log_level)
    assert.is_not_nil(defaults.db_file)
    assert.is_not_nil(defaults.doi_styles)
    assert.is_not_nil(defaults.isbn_styles)
  end)
end)
